# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ('tag_name',),
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=50)),
                ('video_pub_date', models.DateTimeField(verbose_name='date published')),
                ('video_file', models.FileField(upload_to='')),
                ('video_thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('video_views', models.IntegerField(default=0)),
                ('global_tag', models.ManyToManyField(related_name='videos', to='galleryroot.GlobalTag')),
            ],
            options={
                'ordering': ('video_name',),
            },
        ),
    ]
